seed: 42
num_workers: 4
epochs: 13
devices: 4
resume: true
wnb_name: ESFM_s_wm_ci
wnb_id: ESFM_s_wm_ci
learning_rate: 0.0001
stabilise_level_agg: true
variable_aggregation: true
axial_attention: true
num_ensemble: 1
mae_weight: 1.0
nll_weight: 0.0
crps_weight: 0.0
kernel_crps_weight: 0.0
almost_fair_crps_alpha: 0.95
stats_loss_weight: 0.0
lpips_weight: 0.0
use_resolution_specific_patch_tokenizers: false
load_aurora_pretrain_weights: false
log_dir: /iopsstor/scratch/cscs/fozdemir/ESFM_outputs/ESFM_s_wm_ci
data_sources: 
  - era5
mask_config_type: unmaskv3_var5spatial25vertical25
max_grad_norm: 1.0
log_norms: false
log_norm_every_n_steps: 10
log_val_predictions_as_images: false
disable_flashattention: false
add_qk_norm_to_swin3d: true
str_architecture_size: small
strategy: ddp
ddp_find_unused_parameters: true
load_custom_pretrain_weights_str: "/capstor/store/cscs/swissai/a122/ESFM_related/trained_models/esfm_small_aa_unmask3v3_cmip2i/model_ckpt-step=100000-loss_train=0.11.ckpt"
kill_on_nan_detection: true
val_data_sources: 
  - era5_22to25
test_data_sources: 
  - era5_22to25
add_token_pos_embedding_in_decoder: true