image = "ritom_scratch/container-images/torch_physicsnemo_img.sqsh"

writable = true
mounts = ["/users", "/capstor", "/iopsstor", "/ritom"]

[annotations] 
com.hooks.aws_ofi_nccl.enabled = "true" 
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
FI_CXI_DISABLE_HOST_REGISTER = "1"
FI_MR_CACHE_MONITOR = "userfaultfd"


